version: '3.8'

services:
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 99.yoloco
      POSTGRES_DB: clt
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init-db:/docker-entrypoint-initdb.d  # Ruta local con los scripts SQL
    ports:
      - "5431:5432"

  api:
    build:
      context: ./pruebactl
      dockerfile: Dockerfile
    environment:
      - PostgreSQLConnection=Host=db;Port=5432;Database=clt;Username=postgres;Password=99.yoloco;
      - CORS_ORIGINS=http://react-app:80,http://localhost:3000
    depends_on:
      - db
    ports:
      - "5000:8080"

  react-app:
    build:
      context: ./rrhh-front
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:5000/api
    environment:
      - VITE_API_URL=http://localhost:5000/api
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  pgdata: