version: '3.8'

services:
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d  # Ruta local con los scripts SQL
    ports:
      - "5432:5432"

  api:
    build:
      context: ./pruebactl/pruebactl
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__Postgres=Server=db;Port=5432;Database=clt;User=postgres;Password=99.yoloco;
    depends_on:
      - db
    ports:
      - "5000:80"

  react-app:
    build:
      context: ./rrhh-front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  pgdata: